name: Branch-Specific Messages

on:
  push:
    branches:
      - dev
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Print message for dev branch
        if: github.ref == 'refs/heads/dev'
        run: echo "Triggered by dev branch"

      - name: Print message for main branch
        if: github.ref == 'refs/heads/main'
        run: echo "Triggered by main branch"
