name: Accessing My Secret

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Secret
      env:
        MY_SECRET: ${{ secrets.PAT }}
      run: echo $MY_SECRET
