name: Test Schedule

on:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Set Day of Week
        id: day_of_week
        run: echo "DAY_OF_WEEK=$(date +%u)" >> $GITHUB_ENV

      - name: Not on Monday or Wednesday
        if: env.DAY_OF_WEEK != '1' && env.DAY_OF_WEEK != '3'
        run: echo "This step will be skipped on Monday and Wednesday"
        
      - name: Every time
        run: echo "This step will always run"
